apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capd-rke2-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.45.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.46.0.0/16
  topology:
    class: rke2-class
    controlPlane:
      metadata: {}
      replicas: 3
    version: v1.24.6+rke2r1
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 2
